# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CookingScheduler' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'JTAppleCalendar', '~> 6.0'

  pod 'ImageLoader'

  # Pods for CookingScheduler

  target 'CookingSchedulerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CookingSchedulerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
